### PR TITLE
Don't add outputTypeName to InputTypeComposer prefix

### PR DESCRIPTION
**Pull request by stefanprobst**
Currently in `toInputObjectType` the names of the created ITCs are prefixed with the names of their upper-level TCs. This can lead to very long names for deeper nesting levels, and also seems unnecessary since the TC name should already be unique. But I'm not sure if anyone could rely on this naming scheme?

### CODE REVIEW

**Comment by nodkz** [comment]
I'll take a pause about this PR.

Need to remember why I added this field prefix. And what problems will get users in their apps if I merge this PR. It looks like need to bump MAJOR 6.0.0 version.

PS. Maybe it was done for further type modifications, without affecting other models.

PSS You may try the following code:
```js
const AddressTC = UserTC.getFieldTC('address');
AddressTC.toInputObject(); // <-- it will create `AddressInput`
UserTC.toInputObject(); // <-- should reuse `AddressInput`
```

Anyway
Will be cool if we hide your changes under some global flag in `graphql-compose`. I don't know how it can be implemented. Need to see how other nodejs libraries. Something like:
```js
import { set } from 'graphql-compose';
set('noFieldnameForInputs', true);
```
It helps to introduce your changes, without breaking changes for existed users.

**Comment by stefanprobst** [comment]
There's no rush with this!
Just to add a bit more context: what would be great is to call `tc.getITC()`, and have all nesting levels also have their ITC stored on typeComposer.gqType, and with a non-prefixed name. I have another PR that I need to think a bit more about [here](https://github.com/graphql-compose/graphql-compose/compare/master...stefanprobst:setinputtypecomposer).

**Comment by nodkz** [comment]
Feel free to open pr for setInputTypeComposer method. I'll fix typescript definitions tomorrow and with pleasure add your improvement 👍

Tnx!

**Comment by stefanprobst** [comment]
Oh cool thanks!

**Comment by nodkz** [comment]
Thanks, after some pause a found your PR as desired behavior for the graphql type system.

Thanks!

**Pull request merged**
